"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'email': 'a@x.com', 'active': True}, {'email': 'b@x.com', 'active': False}],),
    expected=['a@x.com'],
    description='filter active',
    level="smoke",
)
@case(
    args=([],),
    expected=[],
    description='empty',
    level="smoke",
)
def task_f2_active_emails(a0):
    ...
