"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'id': 'B1', 'severity': 'critical', 'title': 'Crash'}],),
    expected='Crash',
    description='one critical',
    level="smoke",
)
@case(
    args=([],),
    expected='',
    description='empty list',
    level="smoke",
)
@case(
    args=([{'id': 'B1', 'severity': 'minor', 'title': 'Typo'}],),
    expected='',
    description='no critical',
    level="smoke",
)
def task_f1_find_critical(a0):
    ...
