"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'result': 'passed'}, {'result': 'passed'}],),
    expected=True,
    description='all passed',
    level="smoke",
)
@case(
    args=([{'result': 'passed'}, {'result': 'failed'}],),
    expected=False,
    description='one failed',
    level="smoke",
)
@case(
    args=([],),
    expected=True,
    description='empty is all passed',
    level="smoke",
)
def task_f4_all_passed(a0):
    ...
