"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=({'items': [{'category': 'vip'}, {'category': 'normal'}]},),
    expected=True,
    description='has vip',
    level="smoke",
)
@case(
    args=({'items': [{'category': 'normal'}]},),
    expected=False,
    description='no vip',
    level="smoke",
)
@case(
    args=({},),
    expected=False,
    description='no items key',
    level="smoke",
)
def task_f5_vip_in_order(a0):
    ...
