"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'status': 'pending'}, {'status': 'done'}, {'status': 'pending'}],),
    expected=2,
    description='two pending',
    level="smoke",
)
@case(
    args=([],),
    expected=0,
    description='empty',
    level="smoke",
)
def task_f3_count_pending(a0):
    ...
