"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=({'r1': {'model': 'm', 'chunks': [{'chunk_id': 'c1', 'text': 't'}]}},),
    expected=[{'run_id': 'r1', 'model': 'm', 'chunk_id': 'c1', 'chunk_text': 't'}],
    description='one run',
    level="smoke",
)
@case(
    args=({},),
    expected=[],
    description='empty',
    level="smoke",
)
def task_c_flatten(a0):
    ...
