"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=({'a': 3.0, 'b': 1.0, 'c': 2.0}, 2),
    expected={'a': 3.0, 'b': float('-inf'), 'c': 2.0},
    description='top-2',
    level="smoke",
)
@case(
    args=({}, 1),
    expected={},
    description='empty logits',
    level="smoke",
)
def task_g7_top_k_filter(a0, a1):
    ...
