"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([1, 0, 1], [1, 1, 1]),
    expected=0.6666666666666666,
    description='2/3 accuracy',
    level="smoke",
)
@case(
    args=([], []),
    expected=0.0,
    description='empty',
    level="smoke",
)
def task_g4_compute_accuracy(a0, a1):
    ...
