"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([[1, 2], [1]], 0),
    expected={'padded': [[1, 2], [1, 0]], 'attention_mask': [[1, 1], [1, 0]]},
    description='pad batch',
    level="smoke",
)
@case(
    args=([], 0),
    expected={'padded': [], 'attention_mask': []},
    description='empty batch',
    level="smoke",
)
def task_g6_pad_batch(a0, a1):
    ...
