"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([1, 2, 3, 4], 2),
    expected=[1, 2],
    description='truncate',
    level="smoke",
)
@case(
    args=([], 5),
    expected=[],
    description='empty',
    level="smoke",
)
def task_g3_truncate_sequence(a0, a1):
    ...
