"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=({'a': 5, 'b': 1}, 3),
    expected={'a': 5},
    description='min_count 3',
    level="smoke",
)
@case(
    args=({}, 1),
    expected={},
    description='empty vocab',
    level="smoke",
)
def task_g2_vocab_filter(a0, a1):
    ...
