"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=(['a', 'b', 'a'],),
    expected={'a': 2, 'b': 1},
    description='freq',
    level="smoke",
)
@case(
    args=([],),
    expected={},
    description='empty',
    level="smoke",
)
def task_g1_token_frequency(a0):
    ...
