"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'id': 's1', 'tokens': [1, 2]}, {'id': 's2', 'tokens': [1]}],),
    expected={2: ['s1'], 1: ['s2']},
    description='group by len',
    level="smoke",
)
@case(
    args=([],),
    expected={},
    description='empty',
    level="smoke",
)
def task_g5_group_by_length(a0):
    ...
