"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'category': 'food', 'amount': 10}, {'category': 'food', 'amount': 5}],),
    expected={'food': 15},
    description='sum category',
    level="smoke",
)
@case(
    args=([],),
    expected={},
    description='empty',
    level="smoke",
)
def task_d1_orders_by_category(a0):
    ...
