"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'build_id': 'b1', 'duration_sec': 10, 'branch': 'main', 'status': 'failed'}],),
    expected=[{'build_id': 'b1', 'duration_sec': 10, 'branch': 'main'}],
    description='one failed',
    level="smoke",
)
@case(
    args=([{'build_id': 'b1', 'duration_sec': 10, 'branch': 'main', 'status': 'ok'}],),
    expected=[],
    description='none failed',
    level="smoke",
)
def task_d3_failed_builds(a0):
    ...
