"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'rarity': 'rare', 'qty': 2, 'unit_price': 5}],),
    expected={'rare': 10},
    description='value 10',
    level="smoke",
)
@case(
    args=([],),
    expected={},
    description='empty',
    level="smoke",
)
def task_d4_inventory_value(a0):
    ...
