"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'endpoint': '/a', 'ms': 100}, {'endpoint': '/a', 'ms': 300}],),
    expected=[{'endpoint': '/a', 'count': 2, 'avg_ms': 200}],
    description='avg stats',
    level="smoke",
)
@case(
    args=([],),
    expected=[],
    description='empty',
    level="smoke",
)
def task_d5_endpoint_stats(a0):
    ...
