"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'sensor_id': 's1', 'temperature': 90, 'humidity': 10}],),
    expected=['s1'],
    description='temp alert',
    level="smoke",
)
@case(
    args=([{'sensor_id': 's1', 'temperature': 20, 'humidity': 10}],),
    expected=[],
    description='no alert',
    level="smoke",
)
def task_d2_sensor_alerts(a0):
    ...
