"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=({'email': 'a@b.com', 'nested': {'x': 1}},),
    expected={'email': '<REDACTED>', 'nested': {'x': 1}},
    description='dict with email',
    level="smoke",
)
@case(
    args=('plain',),
    expected='plain',
    description='plain string',
    level="smoke",
)
@case(
    args=([],),
    expected=[],
    description='empty list',
    level="smoke",
)
def task_b_sanitize(a0):
    ...
