"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'run_id': 'r1', 'model': 'm', 'prompt': 'p'}], [{'run_id': 'r1', 'chunk_id': 'c1', 'text': 'hi'}], [{'run_id': 'r1', 'tokens_in': 10, 'tokens_out': 5}]),
    expected={'r1': {'model': 'm', 'prompt': 'p', 'chunks': [{'chunk_id': 'c1', 'text': 'hi'}], 'metrics': {'tokens_in': 10, 'tokens_out': 5}}},
    description='basic merge',
    level="smoke",
)
@case(
    args=([], [], []),
    expected={},
    description='all empty',
    level="smoke",
)
def task_a_merge_runs(a0, a1, a2):
    ...
