"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'weight': 2, 'value': 5}, {'weight': 3, 'value': 10}], 3),
    expected={'taken': [{'weight': 2, 'value': 5}], 'total_weight': 2, 'total_value': 5, 'remaining_capacity': 1},
    description='capacity 3',
    level="smoke",
)
@case(
    args=([], 10),
    expected={'taken': [], 'total_weight': 0, 'total_value': 0, 'remaining_capacity': 10},
    description='empty items',
    level="smoke",
)
def task_h4_backpack(a0, a1):
    ...
