"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'name': 'sword', 'qty': 1}, {'name': 'sword', 'qty': 2}],),
    expected={'sword': 3},
    description='stack',
    level="smoke",
)
@case(
    args=([],),
    expected={},
    description='empty',
    level="smoke",
)
def task_h1_inventory_stack(a0):
    ...
