"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=(1, 0, 150),
    expected={'new_level': 2, 'remaining_xp': 0, 'levels_gained': 1},
    description='level up once',
    level="smoke",
)
@case(
    args=(1, 0, 0),
    expected={'new_level': 1, 'remaining_xp': 0, 'levels_gained': 0},
    description='no xp',
    level="smoke",
)
def task_h5_xp_level_up(a0, a1, a2):
    ...
