"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=({'class': 'warrior', 'stats': {'str': 5, 'int': 1, 'agi': 1}},),
    expected=12,
    description='warrior score',
    level="smoke",
)
@case(
    args=({'class': 'mage', 'stats': {'str': 1, 'int': 5, 'agi': 1}},),
    expected=12,
    description='mage score',
    level="smoke",
)
def task_h3_power_score(a0):
    ...
