"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=({'ore': {'C': 7, 'U': 2, 'R': 0}},),
    expected={'ore': {'C': 1, 'U': 1, 'R': 1}},
    description='craft tiers',
    level="smoke",
)
@case(
    args=({},),
    expected={},
    description='empty inventory',
    level="smoke",
)
def task_h8_tiered_synthesis(a0):
    ...
