"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([True, True, True],),
    expected={'total_damage': 40, 'max_combo': 3},
    description='triple combo',
    level="smoke",
)
@case(
    args=([True, False, True],),
    expected={'total_damage': 20, 'max_combo': 1},
    description='break combo',
    level="smoke",
)
def task_h7_combo_system(a0):
    ...
