"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'item': 'gold', 'chance': 100, 'min': 1, 'max': 1}],),
    expected={'gold': 1},
    description='always drop',
    level="smoke",
)
@case(
    args=([],),
    expected={},
    description='empty drops',
    level="smoke",
)
def task_h2_loot_drop(a0):
    ...
