"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=(['sword', 'shield', 'potion'], ['p1', 'p2']),
    expected={'p1': ['sword', 'potion'], 'p2': ['shield']},
    description='round robin',
    level="smoke",
)
@case(
    args=([], ['p1']),
    expected={'p1': []},
    description='no items',
    level="smoke",
)
def task_h6_reward_split(a0, a1):
    ...
