"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'service': 'api', 'status': 200}, {'service': 'api', 'status': 500}],),
    expected=[{'service': 'api', 'total': 2, 'success': 1, 'sla_percent': 50}],
    description='sla 50%',
    level="smoke",
)
@case(
    args=([],),
    expected=[],
    description='empty',
    level="smoke",
)
def task_1_5_sla_report(a0):
    ...
