"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'level': 'ERROR', 'service': 'api'}, {'level': 'ERROR', 'service': 'api'}, {'level': 'INFO', 'service': 'db'}],),
    expected={'api': 2},
    description='count by service',
    level="smoke",
)
@case(
    args=([],),
    expected={},
    description='empty',
    level="smoke",
)
def task_1_2_errors_by_service(a0):
    ...
