"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'level': 'ERROR'}, {'level': 'INFO'}, {'level': 'ERROR'}],),
    expected=2,
    description='two errors',
    level="smoke",
)
@case(
    args=([],),
    expected=0,
    description='empty',
    level="smoke",
)
def task_1_1_count_errors(a0):
    ...
