"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'timestamp': 't1', 'service': 'api', 'response_time_ms': 600}, {'timestamp': 't2', 'service': 'db', 'response_time_ms': 100}],),
    expected=[{'timestamp': 't1', 'service': 'api'}],
    description='one slow',
    level="smoke",
)
@case(
    args=([],),
    expected=[],
    description='empty',
    level="smoke",
)
def task_1_3_slow_requests(a0):
    ...
