"""Smoke tests — generated by scripts/migrate_smoke_format.py.

Full corpus / Hypothesis (@scenario) — later (epic 9u7).
"""

from ego.testing import case

@case(
    args=([{'service': 'api', 'status': 500}, {'service': 'api', 'status': 200}, {'service': 'db', 'status': 500}],),
    expected=['db', 'api'],
    description='unique services',
    level="smoke",
)
@case(
    args=([],),
    expected=[],
    description='empty',
    level="smoke",
)
def task_1_4_services_with_500(a0):
    ...
